# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.4
jobs:
  build-test:
    docker:
      - image: ubuntu:jammy
    resource_class: xlarge
    working_directory: ~/build
    steps:
      - checkout
      - run: 'apt-get update -qq --allow-releaseinfo-change'
      - run: 'apt-get install -y sudo rpm cpio'
      - run: 'apt-get install -y build-essential rsync libtool libncurses5-dev'
      - run: 'apt-get install -y libncursesw5-dev bc pkg-config zsh libelf-dev'
      - run: 'apt-get install -y bison flex binutils-dev gcc libinih-dev'
      - run: 'apt-get install -y uncrustify alien'
      - run: 'apt-get install -y libbpf0'
      - run: 'apt-get install -y libbpf-dev'
      - run: 'apt-get install -y git'      
      - run: 'make btf_circle'
      - run: 'make all'
      - run: 'make rpm'
      - run: 'make deb'
      - run: 'cd ./output && ls'
      - persist_to_workspace:
          root: .
          paths:
            - output
  publish:
    executor: cloudsmith/default
    working_directory: ~/build
    steps:
      - checkout
      - attach_workspace:
          at: ~/build
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run: 'cd ./output && ls'
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/thoth*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/thoth*amd64.deb
          package-format: deb
          package-distribution: ubuntu/jammy

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-test-workflow:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build-test
          filters:
            tags:
              ignore: /test/
            branches:
              ignore: /.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
                - dev
    jobs:
      - build-test
